// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj6Rc-iNAgZlsCUiCiBx4j9VCbtuu7cyY',
    appId: '1:2526571984:web:8a4c4b27e2c9415f999dd5',
    messagingSenderId: '2526571984',
    projectId: 'todo-eae92',
    authDomain: 'todo-eae92.firebaseapp.com',
    storageBucket: 'todo-eae92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHyFaYRLFq16blKkJx-cwURByB-U4mXw',
    appId: '1:2526571984:android:b43ab01e3278dfee999dd5',
    messagingSenderId: '2526571984',
    projectId: 'todo-eae92',
    storageBucket: 'todo-eae92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp8KDowsn4T9TK4wQjmDNeL1vcEj41dLU',
    appId: '1:2526571984:ios:016edaf6447392ab999dd5',
    messagingSenderId: '2526571984',
    projectId: 'todo-eae92',
    storageBucket: 'todo-eae92.appspot.com',
    iosClientId:
        '2526571984-m7uphhuf9r1qmhrj7tf5eqj36pnl9hnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp8KDowsn4T9TK4wQjmDNeL1vcEj41dLU',
    appId: '1:2526571984:ios:3f0e09c222316caa999dd5',
    messagingSenderId: '2526571984',
    projectId: 'todo-eae92',
    storageBucket: 'todo-eae92.appspot.com',
    iosClientId:
        '2526571984-01ffajs0ggfp1f67pnsp84dbkrgitg7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
